# Events
oxygen_passbook_animation_bookings_printing:
    pattern:  /print-bookings/{key}/{id}
    defaults: { _controller: 'OxygenPassbookBundle:Print:bookingsAnimation' }
    requirements:
        key: .+
        id: \d+
    